import {NextResponse} from 'next/server';
import {createReadExchange} from '@/lib/dreamdex';
import {fetchSpotBars} from '@/lib/spot-history';
import {fetchRecentSpotBarsRest} from '@/lib/spot-rest';
import {createStrategyEvaluator,indicatorWarmup,requiredTimeframes,timeframeSeconds,type SpotBar} from '@/lib/strategy-engine';
import type {IndicatorTimeframe,StrategyCondition,StrategySpec,ValueExpr} from '@/lib/types';

const TIMEFRAMES:IndicatorTimeframe[]=['1m','5m','15m','1h','4h'];
const finite=(n:number)=>Number.isFinite(n);
function expressions(c:StrategyCondition):ValueExpr[]{if(c.type==='COMPARE'||c.type==='CROSS')return[c.left,c.right];if(c.type==='TREND')return[c.expr];return[]}
function allExpressions(s:StrategySpec){const out:ValueExpr[]=[];for(const g of s.conditionGroups||[])for(const c of g.conditions)out.push(...expressions(c));return out}
function sameTf(e:ValueExpr,s:StrategySpec,tf:IndicatorTimeframe){return (e.timeframe||s.window)===tf}
function sma(src:number[],period:number){const out=Array(src.length).fill(NaN);let sum=0,valid=0;for(let i=0;i<src.length;i++){const v=src[i];if(finite(v)){sum+=v;valid++}if(i>=period){const old=src[i-period];if(finite(old)){sum-=old;valid--}}if(i>=period-1&&valid===period)out[i]=sum/period}return out}
function ema(src:number[],period:number){const out=Array(src.length).fill(NaN);if(period<1)return out;const k=2/(period+1),seed:number[]=[];let prev=NaN;for(let i=0;i<src.length;i++){const v=src[i];if(!finite(v))continue;if(!finite(prev)){seed.push(v);if(seed.length===period){prev=seed.reduce((a,b)=>a+b,0)/period;out[i]=prev}}else{prev=v*k+prev*(1-k);out[i]=prev}}return out}
function rsi(src:number[],period:number){const out=Array(src.length).fill(NaN);if(src.length<=period)return out;let gain=0,loss=0;for(let i=1;i<=period;i++){const d=src[i]-src[i-1];gain+=Math.max(d,0);loss+=Math.max(-d,0)}let avgG=gain/period,avgL=loss/period;out[period]=avgL===0?100:100-(100/(1+avgG/avgL));for(let i=period+1;i<src.length;i++){const d=src[i]-src[i-1];avgG=(avgG*(period-1)+Math.max(d,0))/period;avgL=(avgL*(period-1)+Math.max(-d,0))/period;out[i]=avgL===0?100:100-(100/(1+avgG/avgL))}return out}
function atr(bars:SpotBar[],period:number){const tr=bars.map((b,i)=>i===0?b.high-b.low:Math.max(b.high-b.low,Math.abs(b.high-bars[i-1].close),Math.abs(b.low-bars[i-1].close)));const out=Array(bars.length).fill(NaN);if(tr.length<period)return out;let v=tr.slice(0,period).reduce((a,b)=>a+b,0)/period;out[period-1]=v;for(let i=period;i<tr.length;i++){v=(v*(period-1)+tr[i])/period;out[i]=v}return out}
function roc(src:number[],period:number){return src.map((v,i)=>i>=period&&finite(src[i-period])&&src[i-period]!==0?((v/src[i-period])-1)*100:NaN)}
function rollingStd(src:number[],period:number){const out=Array(src.length).fill(NaN);for(let i=period-1;i<src.length;i++){const w=src.slice(i-period+1,i+1);if(w.some(v=>!finite(v)))continue;const m=w.reduce((a,b)=>a+b,0)/period;out[i]=Math.sqrt(w.reduce((a,b)=>a+(b-m)**2,0)/period)}return out}
function rollingMax(src:number[],period:number){const out=Array(src.length).fill(NaN);for(let i=period-1;i<src.length;i++){let v=-Infinity;for(let j=i-period+1;j<=i;j++)if(finite(src[j]))v=Math.max(v,src[j]);out[i]=v===-Infinity?NaN:v}return out}
function rollingMin(src:number[],period:number){const out=Array(src.length).fill(NaN);for(let i=period-1;i<src.length;i++){let v=Infinity;for(let j=i-period+1;j<=i;j++)if(finite(src[j]))v=Math.min(v,src[j]);out[i]=v===Infinity?NaN:v}return out}
function stochastic(bars:SpotBar[],period:number,smoothK:number,smoothD:number){const raw=Array(bars.length).fill(NaN);for(let i=period-1;i<bars.length;i++){let hi=-Infinity,lo=Infinity;for(let j=i-period+1;j<=i;j++){hi=Math.max(hi,bars[j].high);lo=Math.min(lo,bars[j].low)}raw[i]=hi===lo?50:((bars[i].close-lo)/(hi-lo))*100}const k=sma(raw,Math.max(1,smoothK)),d=sma(k,Math.max(1,smoothD));return{k,d}}
function vwap(bars:SpotBar[],period:number){const out=Array(bars.length).fill(NaN);let ps=0,vs=0;for(let i=0;i<bars.length;i++){const p=(bars[i].high+bars[i].low+bars[i].close)/3,v=bars[i].volume;ps+=p*v;vs+=v;if(i>=period){const old=bars[i-period],op=(old.high+old.low+old.close)/3;ps-=op*old.volume;vs-=old.volume}if(i>=period-1&&vs>0)out[i]=ps/vs}return out}
function obv(bars:SpotBar[]){const out=Array(bars.length).fill(0);for(let i=1;i<bars.length;i++)out[i]=out[i-1]+(bars[i].close>bars[i-1].close?bars[i].volume:bars[i].close<bars[i-1].close?-bars[i].volume:0);return out}
function shift(src:number[],offset=0){return src.map((_,i)=>i-offset>=0?src[i-offset]:NaN)}
function sourceSeries(e:ValueExpr,bars:SpotBar[]){const closes=bars.map(b=>b.close);if(e.source==='RSI')return rsi(closes,e.sourcePeriod||14);if(e.source==='VOLUME')return bars.map(b=>b.volume);return closes}
function rawSeries(e:ValueExpr,bars:SpotBar[]){const closes=bars.map(b=>b.close),period=e.period||20;let out:number[];
 if(e.kind==='PRICE')out=closes;else if(e.kind==='OPEN')out=bars.map(b=>b.open);else if(e.kind==='HIGH')out=bars.map(b=>b.high);else if(e.kind==='LOW')out=bars.map(b=>b.low);else if(e.kind==='VOLUME')out=bars.map(b=>b.volume);
 else if(e.kind==='RSI')out=rsi(closes,e.period||14);else if(e.kind==='SMA'||e.kind==='EMA'){const src=sourceSeries(e,bars);out=e.kind==='SMA'?sma(src,period):ema(src,period)}
 else if(e.kind==='MACD'||e.kind==='MACD_SIGNAL'){const fast=ema(closes,e.fastPeriod||12),slow=ema(closes,e.slowPeriod||26),m=closes.map((_,i)=>finite(fast[i])&&finite(slow[i])?fast[i]-slow[i]:NaN);out=e.kind==='MACD'?m:ema(m,e.signalPeriod||9)}
 else if(e.kind==='ATR')out=atr(bars,e.period||14);else if(e.kind==='ROC')out=roc(closes,e.period||1);else if(e.kind==='STOCH_K'||e.kind==='STOCH_D'){const st=stochastic(bars,e.period||14,e.smoothK||3,e.smoothD||3);out=e.kind==='STOCH_K'?st.k:st.d}
 else if(e.kind==='VWAP')out=vwap(bars,period);else if(e.kind==='OBV')out=obv(bars);else if(e.kind==='BB_MIDDLE'||e.kind==='BB_UPPER'||e.kind==='BB_LOWER'){const mid=sma(closes,period),sd=rollingStd(closes,period),m=e.stdDev??2;out=mid.map((v,i)=>e.kind==='BB_MIDDLE'?v:e.kind==='BB_UPPER'?v+m*sd[i]:v-m*sd[i])}
 else if(e.kind==='HIGHEST_HIGH')out=rollingMax(bars.map(b=>b.high),period);else if(e.kind==='LOWEST_LOW')out=rollingMin(bars.map(b=>b.low),period);else if(e.kind==='RANGE_WIDTH'){const hi=rollingMax(bars.map(b=>b.high),period),lo=rollingMin(bars.map(b=>b.low),period);out=hi.map((v,i)=>finite(v)&&finite(lo[i])?v-lo[i]:NaN)}
 else if(e.kind==='RANGE_POSITION'){const rangeOffset=Math.max(0,e.offsetBars||0),highs=bars.map(b=>b.high),lows=bars.map(b=>b.low);out=Array(bars.length).fill(NaN);for(let i=0;i<bars.length;i++){const end=i-rangeOffset,start=end-period+1;if(start<0||end<0)continue;let hi=-Infinity,lo=Infinity;for(let j=start;j<=end;j++){hi=Math.max(hi,highs[j]);lo=Math.min(lo,lows[j])}if(finite(hi)&&finite(lo)&&hi>lo)out[i]=((bars[i].close-lo)/(hi-lo))*100}return out.map(v=>finite(v)?v*(e.multiplier??1)+(e.addend??0):NaN)}
 else return null;
 return shift(out,e.offsetBars||0).map(v=>finite(v)?v*(e.multiplier??1)+(e.addend??0):NaN);
}
function exprLabel(e:ValueExpr){const tf=e.timeframe?` ${e.timeframe}`:'',off=e.offsetBars?` · ${e.offsetBars} bar${e.offsetBars===1?'':'s'} back`:'';if(e.kind==='PRICE')return`Price${tf}${off}`;if(e.kind==='OPEN'||e.kind==='HIGH'||e.kind==='LOW'||e.kind==='VOLUME')return`${e.kind[0]}${e.kind.slice(1).toLowerCase()}${tf}${off}`;if(e.kind==='SMA'||e.kind==='EMA'){const src=e.source&&e.source!=='PRICE'?` of ${e.source}${e.source==='RSI'?`(${e.sourcePeriod||14})`:''}`:'';return`${e.kind}(${e.period||20})${src}${tf}${off}`}if(e.kind==='RSI'||e.kind==='ATR'||e.kind==='ROC')return`${e.kind}(${e.period||(e.kind==='ROC'?1:14)})${tf}${off}`;if(e.kind==='MACD')return`MACD(${e.fastPeriod||12},${e.slowPeriod||26})${tf}${off}`;if(e.kind==='MACD_SIGNAL')return`MACD signal(${e.signalPeriod||9})${tf}${off}`;if(e.kind==='STOCH_K'||e.kind==='STOCH_D')return`${e.kind==='STOCH_K'?'Stoch K':'Stoch D'}(${e.period||14})${tf}${off}`;if(e.kind==='VWAP')return`VWAP(${e.period||20})${tf}${off}`;if(e.kind==='OBV')return`OBV${tf}${off}`;if(e.kind.startsWith('BB_'))return`${e.kind.replace('BB_','BB ')}(${e.period||20})${tf}${off}`;if(e.kind==='HIGHEST_HIGH')return`Highest high(${e.period||20})${tf}${off}`;if(e.kind==='LOWEST_LOW')return`Lowest low(${e.period||20})${tf}${off}`;if(e.kind==='RANGE_WIDTH')return`Range width(${e.period||20})${tf}${off}`;if(e.kind==='RANGE_POSITION')return`Range position(${e.period||20})${tf}${off}`;return e.kind}
function panelKey(e:ValueExpr){if(e.kind==='RSI'||((e.kind==='SMA'||e.kind==='EMA')&&e.source==='RSI'))return'RSI';if(e.kind==='VOLUME'||((e.kind==='SMA'||e.kind==='EMA')&&e.source==='VOLUME'))return'VOLUME';if(e.kind==='MACD'||e.kind==='MACD_SIGNAL')return'MACD';if(e.kind==='STOCH_K'||e.kind==='STOCH_D')return'STOCH';if(e.kind==='ATR')return'ATR';if(e.kind==='ROC')return'ROC';if(e.kind==='OBV')return'OBV';if(e.kind==='RANGE_POSITION')return'RANGE_POSITION';if(e.kind==='RANGE_WIDTH')return'RANGE_WIDTH';return null}
function priceOverlay(e:ValueExpr){return e.kind==='PRICE'||e.kind==='OPEN'||e.kind==='HIGH'||e.kind==='LOW'||e.kind==='VWAP'||e.kind==='BB_MIDDLE'||e.kind==='BB_UPPER'||e.kind==='BB_LOWER'||e.kind==='HIGHEST_HIGH'||e.kind==='LOWEST_LOW'||((e.kind==='SMA'||e.kind==='EMA')&&(!e.source||e.source==='PRICE'))}
function panelTitle(k:string){if(k==='STOCH')return'Stochastic';if(k==='RANGE_POSITION')return'Range position';if(k==='RANGE_WIDTH')return'Range width';return k}
function constantValue(e:ValueExpr){if(e.kind!=='CONSTANT'||!finite(e.value??NaN))return null;return (e.value??0)*(e.multiplier??1)+(e.addend??0)}
function technicalOnly(s:StrategySpec){const groups=(s.conditionGroups||[]).map(g=>({...g,conditions:g.conditions.filter(c=>c.type!=='SETTLEMENT_STREAK')})).filter(g=>g.conditions.length);return{...s,conditionGroups:groups}}
function rangeKeys(s:StrategySpec,tf:IndicatorTimeframe){const out=new Map<string,{period:number;offsetBars:number}>();for(const e of allExpressions(s)){if(!sameTf(e,s,tf))continue;if(!['HIGHEST_HIGH','LOWEST_LOW','RANGE_WIDTH','RANGE_POSITION'].includes(e.kind))continue;const period=e.period||20,offsetBars=e.offsetBars||0,k=`${period}:${offsetBars}`;out.set(k,{period,offsetBars})}return [...out.values()]}
function toNullable(a:number[]){return a.map(v=>finite(v)?Number(v.toFixed(8)):null)}
function errText(e:unknown){return e instanceof Error?e.message:String(e)}

export const maxDuration=45;
export async function POST(req:Request){let exchange:any;try{
 const body=await req.json() as {strategy?:StrategySpec;timeframe?:IndicatorTimeframe;limit?:number};const s=body.strategy;if(!s?.asset||!s?.window)throw new Error('A strategy draft is required.');
 const requested=TIMEFRAMES.includes(body.timeframe as IndicatorTimeframe)?body.timeframe:undefined,required=requiredTimeframes(s),available=[...new Set<IndicatorTimeframe>([...(required.length?required:[s.window]),s.window])].sort((a,b)=>timeframeSeconds(a)-timeframeSeconds(b)),tf=requested||available[0],limit=Math.max(40,Math.min(120,Number(body.limit)||72)),now=Math.floor(Date.now()/1000),displayStep=timeframeSeconds(tf),warmup=indicatorWarmup(s),barsByTf:Partial<Record<IndicatorTimeframe,SpotBar[]>>={},sourceByTf:Partial<Record<IndicatorTimeframe,string>>={},warnings:string[]=[];
 const needed=[...new Set<IndicatorTimeframe>([...required,tf])];
 await Promise.all(needed.map(async t=>{
  const wanted=Math.min(500,Math.max(limit+Math.min(warmup,350),120));
  try{const bars=await fetchRecentSpotBarsRest(s.asset,t,wanted);barsByTf[t]=bars;sourceByTf[t]='DreamDEX REST';return}catch(restError){
   try{if(!exchange)exchange=createReadExchange();const span=Math.max(timeframeSeconds(t)*wanted,displayStep*limit);const bars=await fetchSpotBars(exchange,s.asset,t,now-span,now,warmup);if(!bars.length)throw new Error('no candles returned');barsByTf[t]=bars;sourceByTf[t]='DreamDEX indexer';warnings.push(`${t} candles used the DreamDEX indexer fallback because the REST feed was unavailable: ${errText(restError)}`)}catch(indexerError){throw new Error(`${t} chart data failed from both DreamDEX sources. REST: ${errText(restError)}. Indexer: ${errText(indexerError)}`)}
  }
 }));
 const completed=(barsByTf[tf]||[]).filter(b=>b.time+displayStep<=now),display=completed.slice(-limit);if(!display.length)return NextResponse.json({asset:s.asset,timeframe:tf,availableTimeframes:available,bars:[],overlays:[],panels:[],bands:[],markers:[],latestDetails:[],sourceByTf,warnings,warning:'DreamDEX returned no completed spot candles for this view yet.'},{status:503});
 const exprs=allExpressions(s).filter(e=>sameTf(e,s,tf)),seen=new Set<string>(),overlays:{id:string;label:string;kind:string;values:(number|null)[]}[]=[],panelSeries=new Map<string,{id:string;label:string;kind:string;values:(number|null)[]}[]>();
 for(const e of exprs){const k=JSON.stringify(e);if(seen.has(k))continue;const values=rawSeries(e,completed);if(!values)continue;seen.add(k);const row={id:`series-${seen.size}`,label:exprLabel(e),kind:e.kind,values:toNullable(values.slice(-display.length))};if(priceOverlay(e)){if(overlays.length<7)overlays.push(row);continue}const pk=panelKey(e);if(pk){const arr=panelSeries.get(pk)||[];if(arr.length<4)arr.push(row);panelSeries.set(pk,arr)}}
 const refs=new Map<string,{label:string;value:number}[]>();for(const g of s.conditionGroups||[])for(const c of g.conditions){if(c.type!=='COMPARE')continue;const lv=constantValue(c.left),rv=constantValue(c.right);let expr:ValueExpr|null=null,value:number|null=null;if(lv!==null&&c.right.kind!=='CONSTANT'){expr=c.right;value=lv}else if(rv!==null&&c.left.kind!=='CONSTANT'){expr=c.left;value=rv}if(!expr||value===null||!sameTf(expr,s,tf))continue;const pk=panelKey(expr);if(!pk)continue;const arr=refs.get(pk)||[];if(!arr.some(x=>Math.abs(x.value-value!)<1e-9))arr.push({label:c.label,value});refs.set(pk,arr)}
 const panels=[...panelSeries.entries()].slice(0,6).map(([key,series],i)=>({id:`panel-${i+1}`,key,label:panelTitle(key),series,references:refs.get(key)||[]}));
 const bands=rangeKeys(s,tf).slice(0,3).map((r,i)=>{const hi=shift(rollingMax(completed.map(b=>b.high),r.period),r.offsetBars),lo=shift(rollingMin(completed.map(b=>b.low),r.period),r.offsetBars);return{id:`range-${i+1}`,label:`${r.offsetBars?'Previous ':''}${r.period}-bar range`,period:r.period,offsetBars:r.offsetBars,upper:toNullable(hi.slice(-display.length)),lower:toNullable(lo.slice(-display.length))}});
 const technical=technicalOnly(s),ignoredSettlementRules=(s.conditionGroups||[]).reduce((n,g)=>n+g.conditions.filter(c=>c.type==='SETTLEMENT_STREAK').length,0),hasTechnical=!!technical.conditionGroups?.length;let markers:{time:number;price:number;label:string}[]=[],latestDetails:{label:string;passed:boolean;detail:string}[]=[];
 if(hasTechnical){const evaluator=createStrategyEvaluator(technical,barsByTf);markers=display.map(b=>{const r=evaluator.evaluate(b.time+displayStep,[]);return r.passed?{time:b.time,price:b.close,label:'Technical setup matched'}:null}).filter(Boolean).slice(-24) as {time:number;price:number;label:string}[];latestDetails=evaluator.evaluate(display[display.length-1].time+displayStep,[]).details.slice(0,16)}
 return NextResponse.json({asset:s.asset,timeframe:tf,availableTimeframes:available,bars:display.map(b=>({...b,open:Number(b.open.toFixed(8)),high:Number(b.high.toFixed(8)),low:Number(b.low.toFixed(8)),close:Number(b.close.toFixed(8)),volume:Number(b.volume.toFixed(4))})),overlays,panels,bands,markers,latestDetails,ignoredSettlementRules,technicalOnly:ignoredSettlementRules>0,sourceByTf,warnings,updatedAt:Date.now()});
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Could not load the live strategy chart.'},{status:503})}finally{try{await Promise.resolve(exchange?.close?.())}catch{}}}
