'use client';

import {useState} from 'react';
import type {IndicatorTimeframe,StrategySpec} from '@/lib/types';
import type {ChartStrategyEdit} from '@/lib/chart-strategy-edit';
import InteractiveStrategyChart,{type InteractiveChartData} from './InteractiveStrategyChart';
import styles from './StrategyStudio.module.css';

type Reply={summary:string;understood:string[];execution:string[];sizing:string[];risk:string[];assumptions:string[];questions:string[];confidence:number;needsClarification:boolean;compiler:string};
type ChatMessage={id:number;role:'user'|'assistant';content:string;reply?:Reply};

type Props={initialPrompt:string;onDraft?:(strategy:StrategySpec)=>void;onConfirm:(strategy:StrategySpec,transcript:string)=>void};
const welcome='Describe the strategy exactly as you would explain it to another trader. I’ll restate what I think you mean, flag anything ambiguous, and update a live interactive market chart. Nothing becomes executable until you confirm the final rules.';

function buildTranscript(messages:ChatMessage[]){const turns=messages.filter(m=>m.role==='user').slice(-16);return['This is an interactive DreamForge strategy-design conversation.','Treat later user turns as refinements or corrections to earlier turns. Preserve earlier rules unless the user explicitly changes or removes them.','Chart-control messages represent deterministic edits made by the user and must be preserved.','Return the best current deterministic draft and surface any unresolved ambiguity instead of guessing.','',...turns.map((m,i)=>`USER TURN ${i+1}:\n${m.content}`)].join('\n\n')}
function compilerLabel(compiler:string){return compiler==='agent'?'Agent draft':compiler==='deterministic-local'?'Local deterministic':'Safe fallback'}
function replyFrom(s:StrategySpec):Reply{const i=s.interpretation;return{summary:i?.summary||`${s.asset} ${s.window} ${s.side} strategy draft.`,understood:i?.entry||[],execution:i?.execution||[],sizing:i?.sizing||[],risk:i?.risk||[],assumptions:i?.assumptions||[],questions:i?.questions||[],confidence:i?.confidence??0,needsClarification:!!i?.needsClarification,compiler:s.compiler||'agent'}}
function ChatBubble({message}:{message:ChatMessage}){if(message.role==='user')return <div className={`${styles.bubble} ${styles.userBubble}`}><small>YOU</small><p>{message.content}</p></div>;const r=message.reply;return <div className={`${styles.bubble} ${styles.agentBubble}`}><small>DREAMFORGE</small>{r?<><p className={styles.agentSummary}>{r.summary}</p>{r.understood?.length>0&&<div className={styles.chatRules}>{r.understood.slice(0,14).map((x,i)=><div key={i}><span>✓</span><p>{x}</p></div>)}</div>}{r.assumptions?.length>0&&<div className={styles.miniNotice}><b>Assumptions</b>{r.assumptions.map((x,i)=><p key={i}>{x}</p>)}</div>}{r.questions?.length>0&&<div className={`${styles.miniNotice} ${styles.questionNotice}`}><b>Need your answer</b>{r.questions.map((x,i)=><p key={i}>{x}</p>)}</div>}<div className={styles.confidenceRow}><span>{Math.round((r.confidence||0)*100)}% interpretation confidence</span><span>{compilerLabel(r.compiler)}</span></div></>:<p>{message.content}</p>}</div>}

export default function StrategyStudio({initialPrompt,onDraft,onConfirm}:Props){
 const[messages,setMessages]=useState<ChatMessage[]>([{id:1,role:'assistant',content:welcome}]),[input,setInput]=useState(initialPrompt),[draft,setDraft]=useState<StrategySpec|null>(null),[reply,setReply]=useState<Reply|null>(null),[transcript,setTranscript]=useState(''),[busy,setBusy]=useState(false),[chartBusy,setChartBusy]=useState(false),[chart,setChart]=useState<InteractiveChartData|null>(null),[chartError,setChartError]=useState(''),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false);
 const needsClarification=!!reply?.needsClarification||!!draft?.interpretation?.needsClarification,safeCompiler=draft?.compiler==='agent'||draft?.compiler==='deterministic-local',canConfirm=!!draft&&!needsClarification&&safeCompiler&&!busy,chartTimeframes=chart?.availableTimeframes||[];

 async function loadChart(strategy:StrategySpec,timeframe?:IndicatorTimeframe){setChartBusy(true);setChartError('');try{const r=await fetch('/api/chart',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({strategy,timeframe,limit:110}),cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Chart unavailable.');setChart(d)}catch(e:any){setChartError(e.message||'Chart unavailable.')}finally{setChartBusy(false)}}

 async function send(){const text=input.trim();if(!text||busy)return;setBusy(true);setError('');setConfirmed(false);const userMessage:ChatMessage={id:Date.now(),role:'user',content:text},next=[...messages,userMessage];setMessages(next);setInput('');try{const r=await fetch('/api/draft',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messages:next.map(({role,content})=>({role,content}))})});const d=await r.json();if(!r.ok)throw new Error(d.error||'DreamForge could not interpret that refinement.');const rr=d.reply as Reply,agentMessage:ChatMessage={id:Date.now()+1,role:'assistant',content:rr?.summary||'Draft updated.',reply:rr};setMessages(m=>[...m,agentMessage]);setDraft(d.strategy);setReply(rr);setTranscript(d.transcript||buildTranscript(next));onDraft?.(d.strategy);await loadChart(d.strategy)}catch(e:any){setError(e.message||'DreamForge could not update the draft.')}finally{setBusy(false)}}

 async function applyChartEdit(edit:ChartStrategyEdit){if(!draft||busy)return;setBusy(true);setError('');setConfirmed(false);try{const r=await fetch('/api/chart-edit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({strategy:draft,edit})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Chart edit failed.');const s=d.strategy as StrategySpec,rr=replyFrom(s),text=`Chart control deterministic edit: ${JSON.stringify(edit)}. ${d.summary||rr.summary}`,u:ChatMessage={id:Date.now(),role:'user',content:text},a:ChatMessage={id:Date.now()+1,role:'assistant',content:rr.summary,reply:rr},next=[...messages,u,a];setMessages(next);setDraft(s);setReply(rr);setTranscript(buildTranscript(next));onDraft?.(s);await loadChart(s,chart?.timeframe)}catch(e:any){setError(e.message||'Could not apply that chart edit.')}finally{setBusy(false)}}

 async function confirm(){if(!draft||!canConfirm)return;setBusy(true);setError('');try{const finalTranscript=transcript||buildTranscript(messages);let s:StrategySpec=draft;if(draft.compiler==='agent'){const r=await fetch('/api/compile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt:finalTranscript})});s=await r.json();if(!r.ok)throw new Error((s as any).error||'Final compilation failed.')}const finalSafe=s.compiler==='agent'||s.compiler==='deterministic-local';if(!finalSafe||s.interpretation?.needsClarification){setDraft(s);setReply(replyFrom(s));throw new Error('The final deterministic pass still needs clarification. Refine the strategy once more.')}setDraft(s);setConfirmed(true);onConfirm(s,finalTranscript);setMessages(m=>[...m,{id:Date.now()+2,role:'assistant',content:`Strategy confirmed with the ${s.compiler==='agent'?'agent':'local deterministic'} compiler. The exact specification is now locked for backtesting; chart edits or a new message will create a new draft version.`}]);await loadChart(s,chart?.timeframe)}catch(e:any){setError(e.message||'Could not confirm strategy.')}finally{setBusy(false)}}

 return <section className={styles.studio}>
  <div className={styles.studioHead}><div><span>01</span><div><h2>Build the strategy with DreamForge</h2><p>Chat or use the chart itself. Pan, zoom, inspect indicators, click price levels, and rewrite deterministic rules from the chart controls; execution stays locked until you confirm.</p></div></div><div className={`${styles.draftBadge} ${confirmed?styles.confirmed:needsClarification?styles.needsInput:''}`}><b>{confirmed?'CONFIRMED':needsClarification?'NEEDS INPUT':draft?'DRAFT READY':'DRAFT'}</b><small>{draft?`${draft.asset} ${draft.window} · ${draft.side}`:'Not executable'}</small></div></div>
  <div className={styles.workspace}>
   <div className={styles.chatColumn}>
    <div className={styles.chatLog}>{messages.map(m=><ChatBubble key={m.id} message={m}/>)}</div>
    {error&&<div className={styles.errorBox}>{error}</div>}
    <div className={styles.composer}><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();send()}}} placeholder={draft?'Refine it in words, or use the chart controls beside this chat.':'Describe a complex trading idea…'}/><div className={styles.composerActions}><span>Ctrl/⌘ + Enter to send</span><button className={styles.sendButton} onClick={send} disabled={busy||!input.trim()}>{busy?'Updating draft…':draft?'Send refinement':'Interpret strategy'}</button></div></div>
    {draft&&<div className={styles.confirmBar}><div><b>{needsClarification?'DreamForge still needs an answer.':'Satisfied with this interpretation?'}</b><span>{confirmed?'This version is locked for backtesting. Any chart/chat edit creates a new draft.':needsClarification?'Answer in chat or use the chart controls; nothing can be backtested or traded yet.':draft.compiler==='deterministic-local'?'This exact rule set is deterministic and can be confirmed without the AI gateway.':'Run one final deterministic compile and unlock backtesting.'}</span></div><button onClick={confirm} disabled={!canConfirm||confirmed}>{confirmed?'Strategy confirmed':needsClarification?'Resolve questions first':'Confirm strategy'}</button></div>}
   </div>
   <div className={styles.visualColumn}>
    <div className={styles.visualHead}><div><small>INTERACTIVE STRATEGY CHART</small><h3>{draft?`${draft.asset} setup · ${chart?.timeframe||draft.window}`:'Chart appears after the first interpretation'}</h3></div>{chartTimeframes.length>0&&<div className={styles.timeframes}>{chartTimeframes.map(tf=><button key={tf} className={chart?.timeframe===tf?styles.activeTf:''} onClick={()=>draft&&loadChart(draft,tf)} disabled={chartBusy||busy}>{tf}</button>)}</div>}</div>
    {chartBusy&&!chart&&<div className={styles.chartEmpty}>Loading DreamDEX candles, indicators and deterministic annotations…</div>}
    {!chartBusy&&!chart&&!chartError&&<div className={styles.chartEmpty}><b>The chart becomes a strategy editor after the first draft.</b><span>Price clicks, indicator controls and rule chips all update the same deterministic strategy used by the backtest.</span></div>}
    {chartError&&<div className={styles.chartError}>{chartError}</div>}
    {chart&&draft&&<><InteractiveStrategyChart data={chart} strategy={draft} busy={busy||chartBusy} onEdit={applyChartEdit}/>{chart.technicalOnly&&<div className={styles.canvasNote}>Chart markers show the technical portion of the setup. {chart.ignoredSettlementRules} DreamDEX settlement rule{chart.ignoredSettlementRules===1?' is':'s are'} evaluated separately at execution time.</div>}{chart.warnings?.map((w,i)=><div key={i} className={styles.canvasNote}>{w}</div>)}{chart.latestDetails?.length>0&&<div className={styles.ruleMap}><div className={styles.ruleMapHead}><b>Latest completed-bar checks</b><span>{chart.markers?.length||0} recent technical matches shown</span></div>{chart.latestDetails.map((d,i)=><div key={i} className={d.passed?styles.rulePass:styles.ruleWait}><i>{d.passed?'✓':'○'}</i><div><b>{d.label}</b><span>{d.detail}</span></div></div>)}</div>}</>}
    {reply&&<div className={styles.ruleSummary}><div><small>UNDERSTOOD</small><b>{reply.understood.length} entry rule{reply.understood.length===1?'':'s'}</b></div><div><small>ASSUMPTIONS</small><b>{reply.assumptions.length}</b></div><div><small>OPEN QUESTIONS</small><b>{reply.questions.length}</b></div><div><small>CONFIDENCE</small><b>{Math.round(reply.confidence*100)}%</b></div></div>}
   </div>
  </div>
 </section>
}
