import {createReadExchange} from '../lib/dreamdex';
import {createStrategyEvaluator,evaluationStepSeconds,indicatorWarmup,requiredTimeframes,type SpotBar} from '../lib/strategy-engine';
import {fetchSpotBars} from '../lib/spot-history';
import type {StrategySpec} from '../lib/types';

const strategy:StrategySpec={name:'diag',asset:'BTC',window:'15m',side:'UP',trigger:{streakSide:'UP',streakLength:2,maxEntryPrice:.58},conditionGroups:[{logic:'ALL',conditions:[{type:'SETTLEMENT_STREAK',side:'UP',length:2,label:'streak'},{type:'COMPARE',left:{kind:'RSI',period:14,timeframe:'15m'},operator:'GTE',right:{kind:'CONSTANT',value:42},label:'rsi lo'},{type:'COMPARE',left:{kind:'RSI',period:14,timeframe:'15m'},operator:'LTE',right:{kind:'CONSTANT',value:60},label:'rsi hi'},{type:'COMPARE',left:{kind:'EMA',period:20,source:'PRICE',timeframe:'15m'},operator:'GT',right:{kind:'EMA',period:50,source:'PRICE',timeframe:'15m'},label:'ema'},{type:'COMPARE',left:{kind:'VOLUME',timeframe:'15m'},operator:'GT',right:{kind:'SMA',period:20,source:'VOLUME',timeframe:'15m'},label:'vol'}]}],sizing:{baseUsd:8,afterWinUsd:8,afterLossUsd:3},risk:{maxLossUsd:25,maxTrades:12,durationHours:6},compiler:'deterministic-local'};
const now=()=>Date.now();
async function main(){const exchange:any=createReadExchange();try{
 const to=Math.floor(Date.now()/1000)-900,from=to-7*86400,intervalSec=900;
 let t=now();const rows:any[]=[];let offset=0;for(let page=0;page<20;page++){const batch=await exchange.client.listBinaryMarkets({status:'Finalized',asset:'BTC',intervalSec,orderBy:'newest',limit:250,offset} as any);rows.push(...batch);offset+=batch.length;const expiries=batch.map((m:any)=>Number(m.expiry||0)).filter(Boolean);const oldest=expiries.length?Math.min(...expiries):0;if(batch.length<250||(oldest&&oldest<from))break;}console.log('MARKETS_FETCH_MS',now()-t,'ROWS',rows.length);
 const markets=rows.filter((m:any)=>{const e=Number(m.expiry||0);return e>=from&&e<=to&&String(m.asset).toUpperCase()==='BTC'&&Number(m.intervalSec||900)===900}).sort((a:any,b:any)=>Number(a.expiry)-Number(b.expiry));const missing=markets.filter((m:any)=>m.winningOutcome!==0&&m.winningOutcome!==1).length,withTrades=markets.filter((m:any)=>Number(m.tradeCount||0)>0).length;console.log('FILTERED',markets.length,'MISSING_OUTCOME',missing,'WITH_TRADES',withTrades);
 const starts=markets.map((m:any)=>Number(m.tradingStart||Number(m.expiry)-900)).filter((x:number)=>x>0),historyFrom=Math.max(from,starts.length?Math.min(...starts):from),barsByTf:Record<string,SpotBar[]>={};t=now();for(const tf of requiredTimeframes(strategy))barsByTf[tf]=await fetchSpotBars(exchange,'BTC',tf,historyFrom,to,indicatorWarmup(strategy));console.log('SPOT_MS',now()-t,Object.fromEntries(Object.entries(barsByTf).map(([k,v])=>[k,v.length])));
 const evaluator=createStrategyEvaluator(strategy,barsByTf),step=evaluationStepSeconds(strategy),prior:('UP'|'DOWN')[]=[],candidates:any[]=[];t=now();for(const m of markets){const settlement=m.winningOutcome===0?'UP':m.winningOutcome===1?'DOWN':null;if(!settlement)continue;const expiry=Number(m.expiry),start=Number(m.tradingStart||expiry-900);for(let x=start;x<expiry;x+=step){if(evaluator.evaluate(x,prior).passed){candidates.push({market:m,signalTime:x});break}}prior.push(settlement)}console.log('EVAL_MS',now()-t,'CANDIDATES',candidates.length,'CANDIDATES_WITH_TRADES',candidates.filter(c=>Number(c.market.tradeCount||0)>0).length);
 const sample=candidates.filter(c=>Number(c.market.tradeCount||0)>0).slice(0,20);t=now();const settled=await Promise.allSettled(sample.map(c=>exchange.client.getCandles(String(c.market.poolAddress),900,{from:c.signalTime,to:Number(c.market.expiry),limit:20})));console.log('20_HISTORY_MS',now()-t,'OK',settled.filter(x=>x.status==='fulfilled').length,'FAIL',settled.filter(x=>x.status==='rejected').length);
 }finally{try{await Promise.resolve(exchange.close())}catch{}}}
main().catch(e=>{console.error(e);process.exit(1)});
